freebsd_instance:
  image_family: freebsd-12-1-snap

task:
  name: FreeBSD 12.1
  # Install Rust
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain stable
  test_script:
    - . $HOME/.cargo/env
    - cargo test
